//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int BusID { get; set; }
        public string LicensePlates { get; set; }
        public string BusNumber { get; set; }
        public int SumSeats { get; set; }
        public string Status { get; set; }
        public int BusTypeID { get; set; }
        public int RoutesID { get; set; }
    }
}
