//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusRoute()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int BusRouteID { get; set; }
        public string RouteNumber { get; set; }
        public string RouteName { get; set; }
        public int ResponsibleUnitID { get; set; }
        public string OperationType { get; set; }
        public string OperationTime { get; set; }
        public int Fare { get; set; }
        public string BusesAmount { get; set; }
        public string BusesTime { get; set; }
        public string BusesSpace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
    }
}
