//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverID { get; set; }
        public string FullName { get; set; }
        public string IDCard { get; set; }
        public bool Sex { get; set; }
        public System.DateTime DayOfBirth { get; set; }
        public string HomeTown { get; set; }
    }
}
