//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DBAccess
{
    using global::System.Data.Entity;
    using global::System.Data.Entity.Infrastructure;
    using System;
    
    public partial class ROUTE_MANAGEMENTEntities : DbContext
    {
        public ROUTE_MANAGEMENTEntities()
            : base("name=ROUTE_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Stop_Route> Stop_Route { get; set; }
    }
}
