//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string Content { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Comments { get; set; }
        public int NumberOfReviews { get; set; }
        public int NumberOfResponse { get; set; }
        public string CoverImage { get; set; }
        public string Link { get; set; }
        public int TypePostsID { get; set; }
    }
}
