//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BusinessLayer.DBAccess
{
    public partial class Route
    {
        public int RouteID { get; set; }
        public int BusRoutesID { get; set; }
        public int StartPositionID { get; set; }
        public int EndPositionID { get; set; }
        public string RouteName { get; set; }
        public int RouteAmount { get; set; }
        public TimeSpan RouteTime { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public DateTime ApplicableDate { get; set; }
        public DateTime OperationDate { get; set; }
    }
}
