//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Pages
{


	 public partial class WebForm1
	 {

		  /// <summary>
		  /// BusID control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.HtmlControls.HtmlInputText BusID;

		  /// <summary>
		  /// BienSoXe control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.HtmlControls.HtmlInputText BienSoXe;

		  /// <summary>
		  /// SoXe control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl SoXe;

		  /// <summary>
		  /// SoChoNgoi control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl SoChoNgoi;

		  /// <summary>
		  /// TrangThai control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.HtmlControls.HtmlInputText TrangThai;

		  /// <summary>
		  /// bustypelist control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList bustypelist;

		  /// <summary>
		  /// tuyenlist control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList tuyenlist;

		  /// <summary>
		  /// AddBusButton control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button AddBusButton;

		  /// <summary>
		  /// UpdateBusButton control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button UpdateBusButton;

		  /// <summary>
		  /// Button1 control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button Button1;

		  /// <summary>
		  /// Clear control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button Clear;

		  /// <summary>
		  /// Search control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button Search;

		  /// <summary>
		  /// pnPhanTrang control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Panel pnPhanTrang;

		  /// <summary>
		  /// btTruoc control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button btTruoc;

		  /// <summary>
		  /// hPageIndex control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.HiddenField hPageIndex;

		  /// <summary>
		  /// hTotalRows control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.HiddenField hTotalRows;

		  /// <summary>
		  /// hPageSize control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.HiddenField hPageSize;

		  /// <summary>
		  /// pnButton control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Panel pnButton;

		  /// <summary>
		  /// btSau control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button btSau;
	 }
}
