//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ROUTE_MANAGEMENTEntities : DbContext
    {
        public ROUTE_MANAGEMENTEntities()
            : base("name=ROUTE_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<HandlingViolation> HandlingViolations { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Introduction> Introductions { get; set; }
        public virtual DbSet<Reflect> Reflects { get; set; }
        public virtual DbSet<ReflectType> ReflectTypes { get; set; }
        public virtual DbSet<ResponsibleUnit> ResponsibleUnits { get; set; }
        public virtual DbSet<POST> POSTS { get; set; }
        public virtual DbSet<TypePost> TypePosts { get; set; }
    }
}
